name: Release

on:
  push:
    branches:
      - main
    paths:
      - "**.go"

jobs:
  vet-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Test and vet application
        uses: ./.github/actions/vet-test

      - uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: profile.cov

  release:
    runs-on: ubuntu-latest
    needs: vet-and-test
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: go-semantic-release/action@v1
        with:
          hooks: goreleaser
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}