name: Unit tests

on:
  pull_request:
    types: [opened, reopened, synchronize, assigned, review_requested]
  push:
    branches-ignore:
       - main

jobs:
  vet-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Test and vet application
        uses: ./.github/actions/vet-test